name: spade_lite
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animated_floating_buttons: ^0.0.1
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  camera: ^0.10.5+4
  carousel_slider: ^4.0.0
  collection: ^1.17.2
  connectivity_plus: ^5.0.2
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.2.0
  dio: ^5.3.2
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  equatable: ^2.0.5
  expendable_fab: ^0.0.3

  firebase_core: ^2.23.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_card_swiper: ^6.0.0
  flutter_native_splash: null
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0

  flutter_riverpod: ^2.4.3
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  form_validator: ^2.1.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  gestures: ^1.0.0
  get_it: ^7.6.4
  get_storage: ^2.1.1
  giphy_get: ^3.4.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  hexagon: ^0.2.0
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.3
  intl: ^0.18.1
  like_button: ^2.0.5
  lite_rolling_switch: ^1.0.1
  logger: ^2.0.2
  lottie: ^2.7.0
  modal_bottom_sheet: ^3.0.0-pre
  overlay_support: ^2.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  photofilters: ^3.0.1
  pinput: ^3.0.1
  riverpod_annotation: ^2.2.1
  riverpod_lint: ^2.3.1
  shared_preferences: ^2.2.2
  skeletonizer: ^0.8.0
  socket_io_client: ^2.0.3+1
  stacked_list_carousel: ^1.0.1
  story_view: ^0.16.0
  swipe_cards: ^2.0.0+1
  swipe_to: ^1.0.2
  sentry_flutter: ^7.14.0
  table_calendar: ^3.0.9
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.5.1
  timeago: ^3.5.0
  url_launcher: ^6.1.11
  video_player: ^2.7.1
  video_thumbnail: ^0.5.3
  sentry: ^7.14.0
  widget_to_marker: ^1.0.4
  http_parser: ^4.0.2
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  custom_lint: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/onboarding.png
  color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/maptheme/nighttheme.json
    - assets/maptheme/darktheme.json
    - assets/maptheme/aubergine.json
    - assets/maptheme/retro.json
    - assets/maptheme/nightthemelabel.json
    - assets/discover/data.json
    - assets/discover/svgs/
    - assets/discover/animation.json

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets/images
      class_name: SpiderImageAssets
      types: [.svg, .png, .jpg, .jpeg]
    - path: assets/svgs
      class_name: SpiderSvgAssets
      types: [.svg]
