name: spade_v4
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  lite_rolling_switch: ^1.0.1
  custom_radio_grouped_button: ^2.2.0
  percent_indicator: ^4.2.3
  flutter_speed_dial: ^6.2.0
  flutter_svg_icons: ^0.0.1+3
  flutter_staggered_grid_view: ^0.6.2
  table_calendar: ^3.0.9
  flutter_slidable: ^3.0.0
  swipe_to: ^1.0.2
  gestures: ^1.0.0
  carousel_slider: ^4.0.0
  flutter_svg: ^0.23.0+1
  swipe_cards: ^2.0.0+1
  animated_floating_buttons: ^0.0.1
  expendable_fab: ^0.0.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  form_validator: ^2.1.1
  http: ^1.1.0
  dio: ^5.3.2
  csc_picker: ^0.2.7
  shared_preferences: ^2.2.1
  stacked_list_carousel: ^1.0.1
  flutter_card_swiper: ^6.0.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.3
  giphy_get: ^3.4.2
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  bloc: ^8.1.2
  camera: ^0.10.5+4
  video_player: ^2.7.1
  geocoding: ^2.1.0
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  logger: ^2.0.2
  fluttertoast: ^8.2.2
  flutter_riverpod: ^2.4.3
  hexagon: ^0.2.0
  flutter_secure_storage: ^9.0.0
  flutter_native_splash:
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  image: assets/images/onboarding.png
  color: "#f9f9f9"

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/maptheme/nighttheme.json
    - assets/maptheme/darktheme.json
    - assets/maptheme/aubergine.json
    - assets/maptheme/retro.json
    - assets/maptheme/nightthemelabel.json
    - assets/discover/data.json
